### ISSUE TITLE
Code incomplete?

### ISSUE THREAD

**Issue by gencatz** [M4cs/Ethscriptoor#1]
I think the code in index.js is incomplete

const contract = new ethers.Contract(process.env.DEPLOYER_CONTRACT_ADDR);

I get this error when running yarn start locally:

localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/abi/interface.js:1096
if (typeof (value.format) === "function") {
^

TypeError: Cannot read properties of undefined (reading 'format')
at Function.from (localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/abi/interface.js:1096:27)
at new BaseContract (localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/contract/contract.js:519:44)
at new Contract (localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/contract/contract.js:900:1)
at Object. (localpath/Ethscriptoor/src/index.js:12:18)
at Module._compile (node:internal/modules/cjs/loader:1165:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
at Module.load (node:internal/modules/cjs/loader:1043:32)
at Function.Module._load (node:internal/modules/cjs/loader:878:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:22:47
error Command failed with exit code 1.

here ABI and provider should be used or not?

If I add them like const contract = new ethers.Contract(process.env.DEPLOYER_CONTRACT_ADDR, ABI, provider); then I get this running yarn start (after deploying and verifying the contract on goerli testnet)

TypeError: abi is not iterable

Also DEPLOYER_PRIVATE_KEY this is the private key of the eth wallet -> ok
DEPLOYER_CONTRACT_ADDR:  is this the contract address, so what does this mean in Ethscriptoor.sol below:

address public constant DEPLOYER = 0x...; // Change to Deployer address in .env -> not sure what this comment means. Because in .env there is the DEPLOYER_CONTRACT_ADDR (contract address) and DEPLOYER_PRIVATE_KEY (private key of the eth address of the deployer). So what has to be changed in .env ? I just put my eth address there when creating the contract. 

Also is it possible to run yarn start locally to test it or must it run on Google cloud or vps?

**Comment by gencatz** [comment]
This was the error when using just the code on github (after I added this contract = new ethers.Contract(process.env.DEPLOYER_CONTRACT_ADDR, ABI, provider);):


localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/abi/interface.js:1096
        if (typeof (value.format) === "function") {
                          ^

TypeError: Cannot read properties of undefined (reading 'format')
    at Function.from (localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/abi/interface.js:1096:27)
    at new BaseContract (localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/contract/contract.js:519:44)
    at new Contract (localpath/Ethscriptoor/node_modules/ethers/lib.commonjs/contract/contract.js:900:1)
    at Object.<anonymous> (localpath/Ethscriptoor/src/index.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
error Command failed with exit code 1.

**Comment by QuickosssLabs** [comment]
I have the same issue, no news about that ?
